export default (PORT: number | string): {[key: string]: unknown} => ({
  apis: ['./src/app.ts', './src/routes/*.ts'],
  basePath: '/',
  swaggerDefinition: {
    openapi: '3.0.1',
    info: {
      description: 'sensei API with autogenerated swagger doc',
      title: 'sensei API',
      contact: {
        name: 'Ex-Andelan developers'
      },
      servers: [`http://localhost:${PORT}`],
    },
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'apiKey',
          in: 'header',
          description: 'JWT authorization of an API',
          name: 'Authorization',
          bearerFormat: 'JWT'
        }
      }
    }
  }
})
